feat: add i18n
rsksmart/rLogin pull request #115
Opened 2021-08-04 15:47 UTC by lucachaco

2021-08-06 09:51 UTC, jessgusclark requested changes
I think we need to add instructions to the README for developers to choose the default language.

2021-08-06 09:51 UTC, jessgusclark commented on src/ux/step1/WalletProviders.test.tsx
> +    console.log(wrapper.find('h2'))
Let's remove these.

2021-08-06 15:02 UTC, lucachaco commented on src/ux/step1/WalletProviders.test.tsx
> +    console.log(wrapper.find('h2'))
Wow sorry, i missed this

2021-08-09 15:13 UTC, jessgusclark approved these changes

2021-08-09 15:14 UTC, merged