Add ES
rsksmart/rLogin pull request #118
Opened 2021-08-06 06:59 UTC by ilanolkies

2021-08-09 15:17 UTC, lucachaco commented on src/i18n.js
> +      'Get one here!': 'Descargue una aqui!',
aquí

2021-08-09 15:18 UTC, lucachaco commented on src/i18n.js
> +      'Would you like to give us access to info in your data vault?': 'Nos daria acceso a la información requerida de su Data Vault?',
daría

2021-08-09 15:18 UTC, lucachaco commented on src/i18n.js
> +      'Get the information from your Data Vault that you want to share with the following service': 'Descargue la informacion que desea compartir con el servicio',
información

2021-08-09 15:18 UTC, lucachaco commented on src/i18n.js
> +      'Sharing your information is optional. It will only be shared with': 'Compartir su información es opcional. Solo se compartira con',
sólo

2021-08-09 15:19 UTC, lucachaco commented on src/i18n.js
> +      'Confirm Identity': 'Confirmar Identity',
identidad

2021-08-09 15:19 UTC, lucachaco commented on src/i18n.js
> +      'Confirming Identity': 'Confirmando Identity'
identidad

2021-08-09 15:20 UTC, lucachaco requested changes
Just small spelling errors

2021-08-10 12:46 UTC, jessgusclark commented
Rebased from `develop`, changed the base to `develop` and fixed suggestions from @lucachaco

2021-08-10 20:23 UTC, lucachaco approved these changes

2021-08-11 10:03 UTC, jessgusclark commented
GH had an issue last night and the CI didn't run. I have added empty commit to trigger it to run again.

2021-08-11 10:25 UTC, merged