feat: add language selector in footer
rsksmart/rLogin pull request #122
Opened 2021-08-10 20:29 UTC by lucachaco

Pending.
Improve style and connect logic

2021-08-12 10:35 UTC, jessgusclark requested changes
A few things.

the styles for the dropdown are missing:
![image](https://user-images.githubusercontent.com/766679/129182054-daed20f2-bf67-4a39-9ea5-3cafb3fd997f.png)
![image](https://user-images.githubusercontent.com/766679/129182086-9c8f04a6-a0fe-4bcb-a068-9cdf2dc0592d.png)

When I choose Spanish and then click on Metamask, the "connecting" message is still in English:

![Screen Shot 2021-08-12 at 1 30 42 PM](https://user-images.githubusercontent.com/766679/129182207-83e70cf1-9b26-4c59-bab6-009bcc2bdae7.png)

It reverts to English:
  1. Click on connect
  2. change to Spanish
  3. Click on WalletConnect
  4. Close the QR code with the (x)
  5. Click on Login. 
  6. Language is set to English but the text is in Spanish.

Can you add Cypress tests to test the correct functionality? There are a few of them there that should be a good reference.

2021-08-13 23:48 UTC, lucachaco commented
I just thought of pushing the fixes of today so you guys can take a look of the progress so far.

- Selector border remove
- Cypress tests added
- Issue reverting back to english fixed.
Pending: Styling the opened box selector.

![image](https://user-images.githubusercontent.com/85146/129427568-cdf86b62-0a9c-44d1-adee-5f031b0b7929.png)
![image](https://user-images.githubusercontent.com/85146/129427656-e4e34678-f943-49b7-821c-7f1ecf91aba5.png)

2021-08-16 12:43 UTC, jessgusclark requested changes
Worked as expected and the tests were great!!

Just a few CSS changes.

2021-08-16 12:43 UTC, jessgusclark commented on src/ux/step1/WalletProviders.tsx
> +`
It is missing the color, size, and removal of the outline when it is focused. Try this:

```suggestion
const LanguageSelector = styled.select`
  float: left;
  border: 0;
  color: #B0AEB1;
  size: 12px;
  &:focus {
    outline: none;
  }
`
```

2021-08-16 12:43 UTC, jessgusclark commented on src/ux/step1/WalletProviders.tsx
> +  padding: 0 8px 0 8px;
Height should rarely be used. padding would be better:

```suggestion
  padding: 0 8px 25px 8px;
```

2021-08-16 15:41 UTC, lucachaco commented
Thanks for the help on the style @jessgusclark .

- Selector style done
- Cypress tests done
- Issue reverting back to english done.

![image](https://user-images.githubusercontent.com/85146/129590809-da80af06-e91c-43de-858b-4bced205bffd.png)

2021-08-17 03:35 UTC, ilanolkies reviewed
LRGTM!

2021-08-17 03:35 UTC, ilanolkies commented on src/Core.tsx
> +    const availableLanguages = Object.entries(i18next.services.resourceStore.data).map(keyValueLanguage => { return { code: keyValueLanguage[0], name: keyValueLanguage[1].name.toString() } })
We don't need to calculate this in each `render()`. We can do it only once outside the method scope.

2021-08-17 03:35 UTC, ilanolkies commented on src/ux/step1/WalletProviders.tsx
> +      <LanguageSelector onChange={(val) => changeLanguage(val.target.value)} defaultValue={selectedLanguageCode} name="languages" id="languages">
```suggestion
      <LanguageSelector onChange={(e) => changeLanguage(e.target.value)} defaultValue={selectedLanguageCode} name="languages" id="languages">
```

More declarative, for`event`

2021-08-17 20:59 UTC, ilanolkies approved these changes

2021-08-17 21:00 UTC, ilanolkies approved these changes

2021-08-17 21:01 UTC, merged