Fix no credential message
rsksmart/rLogin pull request #124
Opened 2021-08-12 15:40 UTC by diegograsso

Closes #110

2021-08-13 12:23 UTC, jessgusclark submitted a review, later dismissed
Works well. A few thoughts:

1. The link text says "identity manager" but it links to the "issuer". I'm currently working on adding the requests to the manager, so perhaps we should link them there?
2. If I have a credential but not a name declarative detail it does not prompt anything, even though in the backend it says the declarative detail is required. Should this also be accounted for? Perhaps linking to the manager would work for both.
3. Let's add a Cypress test for this. You can mock a response from the datavault. Take a look [at this file](https://github.com/rsksmart/rlogin-sample-apps/blob/main/permissioned-app/frontend-app/cypress/integration/permissioned.spec.js#L33-L37) and the [fixtures here](https://github.com/rsksmart/rlogin-sample-apps/tree/main/permissioned-app/frontend-app/cypress/fixtures)

2021-08-17 03:45 UTC, ilanolkies commented on sample/front/index.html
> +          appUrl: 'https://identity.rifos.org',
We can make this not configurable.

2021-08-17 20:54 UTC, ilanolkies requested changes
Can we make only the word "RIF Identity Manager" a link? With uppers and "RIF"

<img width="461" alt="Screen Shot 2021-08-17 at 17 52 20" src="https://user-images.githubusercontent.com/36084092/129799100-e8e66667-4159-44ac-8440-8686fca18e1f.png">

2021-08-17 22:28 UTC, ilanolkies approved these changes
<img width="473" alt="Screen Shot 2021-08-17 at 19 27 48" src="https://user-images.githubusercontent.com/36084092/129808946-37cd18fa-ba72-4d42-8f78-2d0ee9705270.png">

LRGTM!

2021-08-17 23:49 UTC, merged