select portis network before connect
rsksmart/rLogin pull request #204
Opened 2021-12-09 21:06 UTC by chescalante

https://user-images.githubusercontent.com/8353287/145475622-19971e71-6e1c-42dd-b679-c3562cc10c35.mov

2021-12-10 13:10 UTC, chescalante commented on src/lib/hardware-wallets.ts
> +const PORTIS_NETWORK_PARAMS: NetworkParamsOptions = {
should we rename this file or move portis config into another?

2021-12-10 15:15 UTC, ilanolkies requested changes
We need to update `sample/index.html` to explain how to use it. See https://github.com/rsksmart/rLogin/blob/develop/sample/front/index.html#L114

2021-12-10 15:15 UTC, ilanolkies commented on src/lib/networkOptionsTypes.ts
>  export type NetworkParams = {
```suggestion
export type NetworkParams = TorusNetworkParams | PortisNetworkParams
```

2021-12-13 10:42 UTC, jessgusclark approved these changes
Works good for me. I did submit [an issue with the disabled button](https://github.com/rsksmart/rLogin/issues/205) but that can be done in a different PR.

2021-12-13 19:06 UTC, chescalante commented on src/lib/networkOptionsTypes.ts
>  export type NetworkParams = {
done!

2021-12-21 04:29 UTC, ilanolkies approved these changes

2021-12-21 04:29 UTC, merged