Remove Liquality
rsksmart/rLogin pull request #339
Opened 2024-08-29 16:08 UTC by ronaldsg20

I've updated the `checkRloginInjectedProviders` method in order
		to ensure the Liquality injected provider will be removed from
		the web3modal providers return.

2024-08-29 18:45 UTC, annipi approved these changes
LGTM!

2024-09-05 22:30 UTC, Freshenext approved these changes
We spoke in persona in the hub meetings. The reason is that liquality is no longer maintained and supported. An article will be pasted here so that we know the reason for this merge.

Pending Ronald to put it.

Btw code changes are OK.

2024-09-11 12:15 UTC, jessgusclark requested changes
The changes to `WalletProviders.tsx` is good, but I don't understand the change to injectedProvider.

2024-09-11 12:15 UTC, jessgusclark commented on src/providers/injectedProviders.ts
> +  })
Why are you excluding it? If the user is still using Liquality, for whatever reason, that should be their decision not the developers. Why not just allow it to be shown in the bottom with the other misc providers?

2024-09-17 15:15 UTC, merged